version: "2"
linters:
  enable:
    - forbidigo
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - nolintlint
    - revive
    - tagliatelle
    - thelper
    - tparallel
    - unconvert
    - unparam
    - wastedassign
  settings:
    forbidigo:
      forbid:
        - pattern: ioutil\.*
    tagliatelle:
      case:
        rules:
          json: snake
          yaml: goKebab
        use-field-name: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
